version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: julek200/compose
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/compose
    ports:
      - "3000:3000"
    depends_on:
      - db